- build.gradle
- src/main/java/uk/gov/ida/eventemitter/AmazonEncrypter.java
- src/main/java/uk/gov/ida/eventemitter/AmazonSqsClient.java
- src/main/java/uk/gov/ida/eventemitter/Configuration.java
- src/main/java/uk/gov/ida/eventemitter/Encrypter.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitter.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/main/java/uk/gov/ida/eventemitter/SqsClient.java
- src/main/java/uk/gov/ida/eventemitter/StubEncrypter.java
- src/main/java/uk/gov/ida/eventemitter/StubSqsClient.java
- src/test/java/uk/gov/ida/eventemitter/AmazonEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/AmazonSqsClientTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterTest.java
- src/test/java/uk/gov/ida/eventemitter/StubEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/StubSqsClientTest.java
- src/test/java/uk/gov/ida/eventemitter/TestConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/TestEvent.java
- src/test/java/uk/gov/ida/eventemitter/TestEventEmitterModule.java
These changes enable Event Emitter to encrypt event messages using stub encryption or Amazon encryption service. They also allow Event Emitter to send encrypted messages to either stub SQS service or Amazon SQS service.
Authors: @adityapahuja @michaelwalker
> ABD-35: Update Event Emitter to support encryption and SQS services

- src/main/java/uk/gov/ida/eventemitter/Configuration.java
- src/main/java/uk/gov/ida/eventemitter/Encrypter.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/test/java/uk/gov/ida/eventemitter/AmazonEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/AmazonSqsClientIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/AmazonSqsClientTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterTest.java
- src/test/java/uk/gov/ida/eventemitter/StubEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/StubSqsClientTest.java
- src/test/java/uk/gov/ida/eventemitter/TestConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/TestDecrypter.java
- src/test/java/uk/gov/ida/eventemitter/TestEncrypter.java
- src/test/java/uk/gov/ida/eventemitter/TestEvent.java
- src/test/java/uk/gov/ida/eventemitter/TestEventEmitterModule.java
Update to test an additional field of TestEvent not present in Event interface to ensure that this field is present before and after sending to SQS.
Add TestEncrypter and TestDecrypter to enable an integration test to be able to encrypt an event and decrypt the event properly.
Update EventEmitterModule to drop its attribute Configuration since Configuration cannot be passed through EventEmitterModule's constructor parameter via install() method. @Provides Methods get Configuration via their parameters instead.
Add an integration test to test AmazonSqsClient class. The new integration test tests the failure of sending event message to SQS.
Rename queueName to sourceQueueName to highlight that it is not a dead letter queue.
Authors: @adityapahuja
> ABD-35: Add further test cases to Event Emitter

- .dockerignore
- .gitignore
- Dockerfile
- build.gradle
- pre-commit.sh
I was pretty surprised to see the tests in this (java) project attempt to
download a bunch of python and JS dependencies. Needless to say, my host OS
is not set up with the exact set of versions to install these deps, so the
build fails. Seems like this would be a good use of docker.
> bau: Use docker in pre-commit

- build.gradle
Before we would have missed any deps other than the ones from the root
project's compile and testCompile. This should get them all, regardless
of project structure.
> bau: Nicer / more robust way of downloading deps

- src/main/java/uk/gov/ida/eventemitter/Configuration.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithAMissingS3BucketIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/TestConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/TestEventEmitterModule.java
Change an event emitter to initialise once e.g. to decrypt an event encryption key once after fetching it. Update integration tests to include AWS KMS. LocalStack does not have AWS KMS and it requires integration tests to have mock AWS KMS which can decrypt an event encryption key.
Update an event emitter to override AWS credentials in environment variables if required. It ensures that the event emitter uses its AWS credentials instead of a developer's AWS credentials.
Authors: @adityapahuja
> 335 Decrypt an event encryption key and override AWS credentials in environment variables

- build.gradle
- src/main/java/uk/gov/ida/eventemitter/Configuration.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterConfigurationException.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterBaseConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithAMissingS3BucketIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithDisabledConfigTest.java
- src/test/java/uk/gov/ida/eventemitter/utils/AmazonHelper.java
- src/test/java/uk/gov/ida/eventemitter/utils/TestConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/utils/TestEventEmitterModule.java
* Add new enabled flag to event emitter configuration.
* Can rely on flag rather than absence or presence of relevant config.
* Makes usage explicit and clear.
* Removed use of Optionals in favour of enabled flag.
Co-authored-by: Andy Paine <andy.paine@digital.cabinet-office.gov.uk>
Co-authored-by: dbes-gds <daniel.besbrode@digital.cabinet-office.gov.uk>
https://trello.com/c/8Xm7DiDy/29-deploy-current-mvp-components-in-joint-test-environment
> Trello-8Xm7DiDy: Add enabled flag to config.

- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithDisabledConfigTest.java
Updated test to test the actual config rather than the test config. This also meant passing in null parameters which is what would happen if the config is disabled.
https://trello.com/c/8Xm7DiDy/29-deploy-current-mvp-components-in-joint-test-environment
Co-authored-by: Daniel Besbrode
<daniel.besbrode@digital.cabinet-office.gov.uk>
> Improve test with disabled config

- src/main/java/uk/gov/ida/eventemitter/Configuration.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterBaseConfiguration.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithAMissingS3BucketIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithDisabledConfigTest.java
- src/test/java/uk/gov/ida/eventemitter/utils/TestConfiguration.java
- It seems that when looking up a queue, the account ID of
the account that the application is running in is used
- In joint/other hub envs, we will need to explicitly specify that
the queue is in a different account
> ZD-8Xm7DiDy: Add SQS queue account ID

- src/main/java/uk/gov/ida/eventemitter/EventEmitterConfigurationException.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- We are trying to debug errors in joint and realised that
out exception wrapping was swallowing a lot of the details
about what went wrong
- Make the underlying exception a constructor parameter for
the wrapped exception to make it clear that when using the
EventEmitterConfigurationException, you should pass the original
exception
> TRELLO-8Xm7DiDy: Make exceptions more explicit

- build.gradle
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/main/java/uk/gov/ida/eventemitter/EventEncrypter.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/utils/TestDecrypter.java
The lambda was trying to parse the timestamp as an integer however was receiving a java datetime object. We now parse this to time since epoch in milliseconds.
https://trello.com/c/Qjjmp2cr/84-fix-any-joint-issues
Co-authored-by: Andy Paine <andy.paine@digital.cabinet-office.gov.uk>
> Change timestamp serialization

- src/main/java/uk/gov/ida/eventemitter/Event.java
- src/main/java/uk/gov/ida/eventemitter/EventHasher.java
- src/main/java/uk/gov/ida/eventemitter/EventMessage.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterAmazonEventSenderTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterIntegrationTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterWithDisabledConfigTest.java
- src/test/java/uk/gov/ida/eventemitter/EventEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/EventHasherTest.java
- src/test/java/uk/gov/ida/eventemitter/StubEncrypterTest.java
- src/test/java/uk/gov/ida/eventemitter/StubEventSenderTest.java
- src/test/java/uk/gov/ida/eventemitter/utils/EventMessageBuilder.java
Rest-utils library and Verify Hub are passing in EventSinkHubEvent object to Event Emitter via Event interface. This commit is needed to avoid making code changes to existing code in Verify Hub and Rest Utils library apart from upgrading its dependency to use latest version of event emitter library.
Co-authored-by: adityapahuja <aditya.pahuja@digital.cabinet-office.gov.uk>
Co-authored-by: dbes-gds <daniel.besbrode@digital.cabinet-office.gov.uk>
> TRELLO-W0VXgdcb: Change Event class back to interface

- src/main/java/uk/gov/ida/eventemitter/AmazonEventSender.java
- src/main/java/uk/gov/ida/eventemitter/AwsResponseException.java
- src/test/java/uk/gov/ida/eventemitter/EventEmitterAmazonEventSenderTest.java
- The Amazon client has some built in default retry policies that we
should probably use
- They have the concept of default "retryable" statuses (e.g. 5xx)
- Exception has changed due to a cast going on inside some library
code - the status is also needed to decide if it is "retryable"
> Trello-JJU68z53: Add retry logic

- src/main/java/uk/gov/ida/eventemitter/EventDetailsKey.java
Updated EventDetailsKey enum to include new keys
Co-authored-by: Chris Clayson <chris.clayson@digital.cabinet-office.gov.uk>
> HUB-380: Add Piwik Session ID and Journey Type to events

- build.gradle
This pulls in dropwizard-core 1.3.9 which fixes a number of security
vulnerabilities, namely:
[CVE-2018-19362](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72882)
[CVE-2018-19361](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72884)
[CVE-2018-14718](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72448)
[CVE-2018-19360](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72883)
[CVE-2018-14719](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72450)
[CVE-2018-14721](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72451)
[CVE-2018-14720](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-72449)
[CVE-2018-1000873](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONDATATYPE-173759) …
> BAU Bump dropwizard-logstash to 1.3.9-71

- src/main/java/uk/gov/ida/eventemitter/EventEmitter.java
As the Event Sink MongoDB no longer exists, the only way we will be able to replay messages which failed to send is by capturing them in Kibana.  This is intended to be a stop-gap solution; in the long run we think it would be preferable for user journeys to fail if the audit logger is unavailable.
https://trello.com/c/y8ieTzSO/14-needs-kick-off-adjust-event-emitter-to-log-encrypted-event
In an ideal world, making this change would entail altering/adding tests.  Unfortunately, it is pretty fiddly to check these log messages in much detail - with the addition of the encrypted event, there are now two sections of the log strings which are awkward to check in the tests (the error message, and now additionally the encrypted event).  Prior to this PR, the approach was simply to only check the …
> Add encrypted event when logging errors

- build.gradle
It uses 1.3.12 of dropwizard rather than 1.3.9 which was susceptible to
a couple of CSVs.
> BAU Upgrade dropwizard-logstash to 1.3.12-72

- .travis.yml
- Dockerfile
- PublicDockerfile
- pre-commit.sh
- src/intTest/java/uk/gov/ida/eventemitter/sqs/AmazonSqsClientIntegrationTest.java
- Reinstated Dockerfiles as they are used by the Jenkins build.
- Made sure that the Localstack Integration tests execute successfully under Docker.
- pre-commit now runs under Docker again, including the integrationTest task.
Co-authored-by: Alex Wilson <alex.wilson@digital.cabinet-office.gov.uk>
> OGD-99: DCS SQS Fix Jenkins Build

- build.jenkins
- Tests are not currently running.
- Update build command to run unit and integration tests.
Co-authored-by: Alex Wilson <alex.wilson@digital.cabinet-office.gov.uk>
> OGD-152: Run Tests in Event Emitter Jenkins Build

- src/intTest/java/uk/gov/ida/eventemitter/sqs/EventEmitterSQSIntegrationTest.java
- src/main/java/uk/gov/ida/eventemitter/EventEmitterModule.java
- src/main/java/uk/gov/ida/eventemitter/sqs/EventEmitterSQSModule.java
- src/test/java/uk/gov/ida/eventemitter/sqs/EventEmitterSQSModuleTest.java
- src/test/java/uk/gov/ida/eventemitter/sqs/EventEmitterSQSTestHelper.java
- Including SQS Providers in the EventEmitterModule caused issues in Staging as Guice tries to instantiate everything in the module, even if it is not used in code.
- Moved all SQS related Providers to a separate module which will not be added to Guice if not needed.
- Additional tests added to capture circumstances of failure in Staging.
Co-authored-by: Alex Wilson <alex.wilson@digital.cabinet-office.gov.uk>
> OGD-138: Refactor Event Emitter SQS Module

- Dockerfile
- PublicDockerfile
- src/intTest/java/uk/gov/ida/eventemitter/sqs/AmazonSqsClientIntegrationTest.java
- Stop using the Verify custom java8 docker image and use the openjdk 11 image instead.
> BAU - Use java11 docker image

- src/main/java/uk/gov/ida/eventemitter/EventDetailsKey.java
This PR is 1 part of several across Verify to be able to support billing for new special case `LOA2,LOA1/exact` requests. It adds two new details keys for events to support the information that will be emitted by the hub, and eventually recorded in the billing and audit tables.
The full set of changes being made is laid out in:
* [ADR 36 billing changes plan](https://docs.google.com/document/d/1hblVU0wquj6Z3-b9V75z6jb1wt3Nnpjh2MNHxNGgTBE/edit?usp=sharing)
For context, please see:
* [ADR 35](https://github.com/alphagov/verify-architecture/blob/master/adr/0035-allow-specified-loa2-services-to-receive-loa1-identities.md) (sending LOA2,LOA1/exact requests to IDPs)
* [ADR 36](https://github.com/alphagov/verify-architecture/blob/master/adr/0036-support-billing-on-provided-loa.md) (changes to …
> Add preferred and maximum level of assurance event detail keys

- src/main/java/uk/gov/ida/eventemitter/EventDetailsKey.java
- We no use the required_level_of_assurance so we can remove it.
Co-authored-by: Lewis Westbury <lewis.wetbury@digital.cabinet-office.gov.uk>
> Remove required_level_of_assurance

- build.gradle
- src/intTest/java/uk/gov/ida/eventemitter/sqs/AmazonSqsClientIntegrationTest.java
Bintray and jcenter are going away. This updates the public builds to
pull from maven central. It also bumps versions of our libs to ensure
they're being pulled from maven central.
Also removes the redundant `apply` for the nexus publishing plugin. The
plugin block applies if for us.
The version of localstack we were using was a little out of date and not
working. This bumps to the latest versions and configures it correctly.
The error message in the second integration test now returns a random
request ID, so the expected string has been shortened. The test
frameworks checks that the expected string is a substring of the actual
message, so this still works and checks what we actually care about.
> HUB-908: Pull from maven central

- .github/workflows/pre-merge-checks.yml
- src/main/java/uk/gov/ida/eventemitter/sqs/AmazonSqsClient.java
- src/test/java/uk/gov/ida/eventemitter/sqs/AmazonSqsClientTest.java
- We need to register the JodaModule on the ObjectMapper due to the upgrade of dropwizard-logstash which uplifted jackson. This is because Joda datatypes are no longer supported by default.
- Add github actions to catch failures before merging
> BAU - Fix unit tests and add github actions
